<a href="https://colab.research.google.com/github/guruboy001/gurucodes/blob/master/365_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd 
import numpy as np

In [0]:
data = pd.read_csv('/content/data_365_processed.csv')

In [141]:
data.head()

first_reason  second_reason  ...  Pets  Absenteeism Time in Hours
0             0              0  ...     1                          4
1             0              0  ...     0                          0
2             0              0  ...     0                          2
3             1              0  ...     0                          4
4             0              0  ...     1                          2

[5 rows x 15 columns]

Lets find the mean of the Absenteeism and set the value as our threshold. that is a value less will be assign 0 and a value greater will be assigned 1. This helps to simplify our classification algorithm.

In [142]:
threshold = data['Absenteeism Time in Hours'].median()
threshold

3.0

In [0]:
targets = np.where(data['Absenteeism Time in Hours']>threshold,1,0) 

In [144]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [0]:
data['Absolute Absenteeism']=targets

In [146]:
data.head()

first_reason  second_reason  ...  Absenteeism Time in Hours  Absolute Absenteeism
0             0              0  ...                          4                     1
1             0              0  ...                          0                     0
2             0              0  ...                          2                     0
3             1              0  ...                          4                     1
4             0              0  ...                          2                     0

[5 rows x 16 columns]

In [0]:
#training_data = data.drop(['Absenteeism Time in Hours'],axis=1)
training_data = data.drop(['Absenteeism Time in Hours','Daily Work Load Average'],axis=1)

checking if training_data has the same memory location as data

In [148]:
training_data is data

False

In [0]:
unscaled_input = training_data.iloc[:,:-1]

In [0]:
from sklearn.preprocessing import StandardScaler

absent_scaler = StandardScaler()

In [151]:
absent_scaler.fit(unscaled_input)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
scaled_inputs = absent_scaler.transform(unscaled_input)

In [153]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.39626354, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.39626354, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [0]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size=0.8,random_state=42)

In [155]:
print(x_train.shape,y_train.shape)

(560, 13) (560,)


In [156]:
print(x_test.shape,y_test.shape)

(140, 13) (140,)


In [0]:
from sklearn import metrics
from sklearn.linear_model import LogisticRegression

reg = LogisticRegression()

In [158]:
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [159]:
reg.score(x_train,y_train)

0.7946428571428571

In [0]:
predicting = reg.predict(x_train)

In [161]:
print((predicting==y_train).mean())

0.7946428571428571


In [162]:
np.sum(predicting==y_train)

445

In [163]:
len(y_train)

560

In [164]:
np.sum(predicting==y_train)/len(y_train)

0.7946428571428571

In [165]:
reg.coef_

array([[ 1.94843979,  0.3134256 ,  1.68482886,  1.12740846,  0.1408849 ,
        -0.156398  ,  0.6667021 , -0.10001487, -0.2739389 ,  0.23125552,
        -0.21275269,  0.40247329, -0.53398197]])

In [166]:
reg.intercept_

array([-0.08773424])

In [0]:
feature_name = unscaled_input.columns.values

In [0]:
summary_table = pd.DataFrame(columns=['feature_name'],data=feature_name)
summary_table['coefficient'] = np.transpose(reg.coef_)

In [169]:
summary_table

feature_name  coefficient
0             first_reason     1.948440
1            second_reason     0.313426
2             third_reason     1.684829
3             fourt_reason     1.127408
4                   months     0.140885
5                     days    -0.156398
6   Transportation Expense     0.666702
7         Distance to Work    -0.100015
8                      Age    -0.273939
9          Body Mass Index     0.231256
10               Education    -0.212753
11                Children     0.402473
12                    Pets    -0.533982

In [170]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

feature_name  coefficient
0                intercept    -0.087734
1             first_reason     1.948440
2            second_reason     0.313426
3             third_reason     1.684829
4             fourt_reason     1.127408
5                   months     0.140885
6                     days    -0.156398
7   Transportation Expense     0.666702
8         Distance to Work    -0.100015
9                      Age    -0.273939
10         Body Mass Index     0.231256
11               Education    -0.212753
12                Children     0.402473
13                    Pets    -0.533982

In [0]:
summary_table['logOdds'] = np.exp(summary_table.coefficient)

In [172]:
summary_table

feature_name  coefficient   logOdds
0                intercept    -0.087734  0.916004
1             first_reason     1.948440  7.017730
2            second_reason     0.313426  1.368104
3             third_reason     1.684829  5.391528
4             fourt_reason     1.127408  3.087644
5                   months     0.140885  1.151292
6                     days    -0.156398  0.855219
7   Transportation Expense     0.666702  1.947803
8         Distance to Work    -0.100015  0.904824
9                      Age    -0.273939  0.760379
10         Body Mass Index     0.231256  1.260181
11               Education    -0.212753  0.808356
12                Children     0.402473  1.495519
13                    Pets    -0.533982  0.586266

Creating a Transformer

In [0]:
from sklearn.base import TransformerMixin, BaseEstimator

class Scaler(BaseEstimator,TransformerMixin):

    def __init__(self,columns,with_mean=True,with_std=True,copy=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_  = None

    def fit(self,X,y=None):
        self.scaler.fit(X[self.columns],y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self,X,y=None,copy=None):
        init_column = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
        X_unscaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_scaled,X_unscaled],axis=1)[init_column]


In [174]:
unscaled_input.columns.values


array(['first_reason', 'second_reason', 'third_reason', 'fourt_reason',
       'months', 'days', 'Transportation Expense', 'Distance to Work',
       'Age', 'Body Mass Index', 'Education', 'Children', 'Pets'],
      dtype=object)

In [0]:
'''columns_to_scale = ['months', 'days', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']'''
omited_column = ['Daily Work Load Average','first_reason', 'second_reason', 'third_reason', 'fourt_reason']
columns_to_scale = [X for X in unscaled_input.columns.values if X not in omited_column]


In [0]:
absentieesm_scaler = Scaler(columns_to_scale)

In [181]:
absentieesm_scaler.fit(unscaled_input)

/usr/local/lib/python3.6/dist-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


Scaler(columns=['months', 'days', 'Transportation Expense', 'Distance to Work',
                'Age', 'Body Mass Index', 'Education', 'Children', 'Pets'],
       copy=None, with_mean=None, with_std=None)

In [0]:
scaled_input = absentieesm_scaler.transform(unscaled_input)

In [183]:
scaled_input

first_reason  second_reason  third_reason  ...  Education  Children      Pets
0               0              0             0  ...  -0.447980  0.880469  0.268487
1               0              0             0  ...  -0.447980 -0.019280 -0.589690
2               0              0             0  ...  -0.447980 -0.919030 -0.589690
3               1              0             0  ...  -0.447980  0.880469 -0.589690
4               0              0             0  ...  -0.447980  0.880469  0.268487
..            ...            ...           ...  ...        ...       ...       ...
695             1              0             0  ...   2.232242  0.880469 -0.589690
696             1              0             0  ...  -0.447980 -0.019280  1.126663
697             1              0             0  ...   2.232242 -0.919030 -0.589690
698             0              0             0  ...   2.232242 -0.919030 -0.589690
699             0              0             0  ...  -0.447980 -0.019280  0.268487

[700 rows x 13 columns]

In [0]:
x_train,x_test,y_train,y_test = train_test_split(scaled_input,targets,train_size=0.8,random_state=42)

In [185]:
reg.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
pred = reg.predict(x_train)

In [187]:
print(np.mean(y_train==pred))

0.7857142857142857


In [0]:
pred1 = reg.predict(x_test)

In [189]:
print(np.mean(pred1==y_test))

0.8


As we can see from the model some information are not necessary and contribute little or no influence to the accuracy of our model. Therefore we will be removing them.

In [190]:
reg.score(x_test,y_test)

0.8

In [0]:
prob = reg.predict_proba(x_test)

In [0]:
prob1 = prob[:,1]

In [194]:
prob1

array([0.17860939, 0.11689534, 0.86098145, 0.38393399, 0.43708857,
       0.90196154, 0.25342923, 0.58038865, 0.24065622, 0.29066153,
       0.10022834, 0.24741508, 0.7713747 , 0.3097279 , 0.19397278,
       0.55000247, 0.08254225, 0.69026204, 0.09715922, 0.34397391,
       0.32321521, 0.22264533, 0.27458769, 0.26132907, 0.14163171,
       0.79945063, 0.3285733 , 0.38229192, 0.19967339, 0.32100654,
       0.11216046, 0.16576688, 0.95857919, 0.93814445, 0.18275776,
       0.69677736, 0.23375502, 0.16637128, 0.85814271, 0.17217849,
       0.567017  , 0.23560242, 0.45607386, 0.13392545, 0.17852729,
       0.70239472, 0.79024431, 0.89921262, 0.28239747, 0.12564105,
       0.22867438, 0.26776837, 0.38491328, 0.94522899, 0.176164  ,
       0.23099187, 0.97190534, 0.21720739, 0.86274965, 0.22429035,
       0.42838846, 0.13960235, 0.49577953, 0.58038865, 0.10022834,
       0.3731561 , 0.69546191, 0.07844829, 0.22388887, 0.52324319,
       0.29066153, 0.21747235, 0.76266914, 0.26776837, 0.12145

# Saving our model using pickle
 
 The model can be saved using the pickle library and later unloaded for use just like joblib

In [0]:
import pickle

In [0]:
with open('model','wb') as file:
    pickle.dump(reg,file)


In [0]:
with open('scaler','wb') as file:
    pickle.dump(absentieesm_scaler,file)