<a href="https://colab.research.google.com/github/guruboy001/gurucodes/blob/master/SalePricePredication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np


In [0]:
train = pd.read_csv("kaggle house/train.csv")

In [0]:
test = pd.read_csv("kaggle house/test.csv")

In [81]:
train.head()

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [82]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

In [0]:
Id = y_train = train['Id'].copy()

In [0]:
train.drop('Id',axis=1,inplace=True)
test.drop('Id',axis=1,inplace=True)

In [85]:
train['Alley'].value_counts()

Grvl    50
Pave    41
Name: Alley, dtype: int64

In [0]:
train.drop('Alley',axis=1,inplace=True)
test.drop('Alley',axis=1,inplace=True)

In [87]:
train['PoolQC'].value_counts()

Gd    3
Ex    2
Fa    2
Name: PoolQC, dtype: int64

In [0]:
train.drop('PoolQC',axis=1,inplace=True)
test.drop('PoolQC',axis=1,inplace=True)

In [89]:
train['MiscFeature'].value_counts()

Shed    49
Othr     2
Gar2     2
TenC     1
Name: MiscFeature, dtype: int64

In [0]:
train.drop('MiscFeature',axis=1,inplace=True)
test.drop('MiscFeature',axis=1,inplace=True)

In [91]:
train['Fence'].value_counts()

MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: Fence, dtype: int64

In [0]:
train.drop('Fence',axis=1,inplace=True)
test.drop('Fence',axis=1,inplace=True)

In [0]:
y_train = train['SalePrice'].copy()


In [0]:
train.drop('SalePrice',axis=1,inplace=True)


In [0]:

from sklearn.base import BaseEstimator, TransformerMixin

class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names]

In [0]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

num_pipeline = Pipeline([
        ("select_numeric", DataFrameSelector(["LotFrontage","MasVnrArea","GarageYrBlt"])),
        ("imputer", SimpleImputer(strategy="median")),
    ])

In [0]:
class MostFrequentImputer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        self.most_frequent_ = pd.Series([X[c].value_counts().index[0] for c in X],
                                        index=X.columns)
        return self
    def transform(self, X, y=None):
        return X.fillna(self.most_frequent_)

In [0]:
from sklearn.preprocessing import OneHotEncoder

In [0]:
from sklearn.impute import SimpleImputer

cat_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["MasVnrType","BsmtQual","BsmtCond","BsmtExposure","BsmtFinType1","BsmtFinType2","Electrical","FireplaceQu","GarageType","GarageFinish","GarageQual","GarageQual"])),
        #("imputer", MostFrequentImputer()),
        ("imputer",SimpleImputer(strategy='most_frequent')),
        ("cat_encoder", OneHotEncoder(sparse=False)),
    ])

In [110]:
cat_pipeline.fit_transform(train)

array([[0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.]])

In [101]:
num_pipeline.fit_transform(train)

array([[  65.,  196., 2003.],
       [  80.,    0., 1976.],
       [  68.,  162., 2001.],
       ...,
       [  66.,    0., 1941.],
       [  68.,    0., 1950.],
       [  75.,    0., 1965.]])

In [0]:
from sklearn.pipeline import FeatureUnion
preprocess_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", num_pipeline),
        ("cat_pipeline", cat_pipeline),
    ])

In [112]:
X_train = preprocess_pipeline.fit_transform(train)
X_train

array([[6.500e+01, 1.960e+02, 2.003e+03, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [8.000e+01, 0.000e+00, 1.976e+03, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [6.800e+01, 1.620e+02, 2.001e+03, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       ...,
       [6.600e+01, 0.000e+00, 1.941e+03, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [6.800e+01, 0.000e+00, 1.950e+03, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [7.500e+01, 0.000e+00, 1.965e+03, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [116]:
forest_clf = RandomForestClassifier(n_estimators=100, random_state=42)
forest_scores = cross_val_score(forest_clf, X_train, y_train, cv=10)
forest_scores.mean()

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)


0.0061643835616438354

In [0]:
X_test = preprocess_pipeline.fit_transform(test)

In [119]:
forest_clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [120]:
price = forest_clf.predict(X_test)

ValueError: ignored